# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [master, dev]
  pull_request:
    branches: [master, dev]
defaults:
  run:
    working-directory: server

jobs:
  test:
    name: "${{ matrix.os }} -> node ${{ matrix.node-version }} "
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        node-version: [10.x, 12.x, 14.x]
        os: [ubuntu-latest]

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - run : docker-compose up -d
        working-directory: server/database
        env: 
          POSTGRES_PASSWORD: ${{secrets.POSTGRES_PASSWORD}}
          POSTGRES_USER: ${{secrets.POSTGRES_USER}}
          POSTGRES_DB: ${{secrets.POSTGRES_DB}}
        name: Create database
        
      - run: yarn
        name: install dependencies
      
      - run: yarn test
        env:
          GOOGLE_CLIENT_ID: ${{secrets.GGL_LOG}}
          GOOGLE_CLIENT_SECRET: ${{secrets.GGL_SECRET}}
          TOKEN_SECRET: ${{secrets.TOKEN_SECRET}}
          JWT_TOKEN: ${{secrets.JWT_TOKEN}}
          POSTGRES_PASSWORD: ${{secrets.POSTGRES_PASSWORD}}
          POSTGRES_USER: ${{secrets.POSTGRES_USER}}
          POSTGRES_DB: ${{secrets.POSTGRES_DB}}
        name: run tests
          
